import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {FiGrid, FiPackage, FiPlusCircle, FiSearch, FiSettings} from "react-icons/fi";
import Link from "next/link";
import React from "react";
import {ApolloWrapper} from "@/lib/apollo/ApolloWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {/* Sidebar */}
      <div className="fixed left-0 top-0 h-screen w-16 bg-white shadow-lg flex flex-col items-center py-4 space-y-8">
        <div className="text-blue-600 p-2">
          <FiPackage size={24} />
        </div>
        <nav className="flex-1 flex flex-col items-center space-y-4">
          <Link href="/" className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg">
            <FiGrid size={20} />
          </Link>
          <Link href="/products/new" className="p-2 text-gray-600 hover:bg-blue-50 rounded-lg">
            <FiPlusCircle size={20} />
          </Link>
          <Link href="/products/search" className="p-2 text-gray-600 hover:bg-blue-50 rounded-lg">
            <FiSearch size={20} />
          </Link>
          <Link href="/settings" className="p-2 text-gray-600 hover:bg-blue-50 rounded-lg">
            <FiSettings size={20} />
          </Link>
        </nav>
      </div>
      <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
